<?php
/**
 * Created by PhpStorm.
 * User: sunkeyi
 * Date: 2017/5/1
 * Time: 下午5:16
 */
echo "这是注册页面";

echo $this->tag->form('signup/register'); ?>

<p>
	<label for="name">
		Name
	</label>

	<?php echo $this->tag->textField("name"); ?>
</p>

<p>
	<label for="email">
		E-Mail
	</label>

	<?php echo $this->tag->textField("email"); ?>
</p>



<p>
	<?php echo $this->tag->submitButton("Register"); ?>
</p>

</form>
